{% set version = "4.4.1" %}
{% set description = "AscatNGS contains the Cancer Genome Projects workflow implementation of the ASCAT copy number algorithm for paired end sequencing." %}
{% set url = "https://github.com/cancerit/ascatNgs" %}

package:
  name: ascatngs
  version: {{ version }}

# More details on https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
source:
  git_url: {{ url }}
  git_rev: {{ version }}
  git_depth: 1


build:
  include_recipe: True
  script: bash setup.sh

requirements:
  build:
    - r-base
    - gxx
    - make
    - gcc
    - wget
    - pkg-config
    - gfortran
    - unzip
    - tzdata
    - libxml2
    - libgit2
    - libblas
    - libboost
    - perl-app-cpanminus

  run:
    - r-base
    - perl

test:
  imports:

about:
  home: {{ url }}
  license: AGPL
  license_file: LICENSE
  license_family: AGPL

  summary: {{ description }}
  description: {{ description }}
  doc_url: https://github.com/cancerit/ascatNgs/blob/master/README.md
  dev_url: {{ url }}