name: release-package
on:
  push:
    tags:
      - v*
    branches:
      - master    

jobs:
  release-package:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        subdir: ["ascatNgs"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: biominer-lab,conda-forge,bioconda,defaults
          channel-priority: true
          auto-update-conda: true
      - name: Install conda-build
        shell: bash -l {0}
        # Error: expected str, bytes or os.PathLike object, not list
        # More details on https://github.com/conda/conda-build/issues/4222
        run: mamba install conda-build anaconda-client
      - name: Package & Release
        shell: bash -l {0}
        run: mamba build conda.recipe --token ${{ secrets.ANACONDA_TOKEN }} --user biominer-lab --skip-existing --output-folder build
        working-directory: ${{ matrix.subdir }}